"""
Monitoring module for MineralVision.

Provides real-time monitoring and automated model retraining capabilities.
"""

from .realtime_dashboard import (
    MetricType,
    AlertSeverity,
    AlertStatus,
    DashboardPanel,
    MetricCollector,
    CounterMetric,
    GaugeMetric,
    HistogramMetricCollector,
    InferenceLatencyCollector,
    PipelineThroughputCollector,
    StorageUtilizationCollector,
    DriftMetricsCollector,
    AlertManager,
    MetricsRegistry,
    DashboardBuilder,
    MonitoringService,
    create_monitoring_service,
    create_alert_manager,
    create_metrics_registry,
)

from .auto_retraining import (
    RetrainingTrigger,
    ModelStage,
    TrainingStatus,
    ABTestStatus,
    RollbackReason,
    TrainingConfig,
    TrainingMetrics,
    TrainingJob,
    ModelVersion,
    ABTestConfig,
    ABTestResult,
    RollbackEvent,
    RetrainingSchedule,
    DriftTriggerEvaluator,
    PerformanceMonitor,
    ABTestManager,
    RollbackManager,
    TrainingJobQueue,
    AutoRetrainingPipeline,
    create_auto_retraining_pipeline,
    create_ab_test_manager,
    create_rollback_manager,
)

__all__ = [
    # Real-time Dashboard
    'MetricType',
    'AlertSeverity',
    'AlertStatus',
    'DashboardPanel',
    'MetricCollector',
    'CounterMetric',
    'GaugeMetric',
    'HistogramMetricCollector',
    'InferenceLatencyCollector',
    'PipelineThroughputCollector',
    'StorageUtilizationCollector',
    'DriftMetricsCollector',
    'AlertManager',
    'MetricsRegistry',
    'DashboardBuilder',
    'MonitoringService',
    'create_monitoring_service',
    'create_alert_manager',
    'create_metrics_registry',
    # Auto Retraining
    'RetrainingTrigger',
    'ModelStage',
    'TrainingStatus',
    'ABTestStatus',
    'RollbackReason',
    'TrainingConfig',
    'TrainingMetrics',
    'TrainingJob',
    'ModelVersion',
    'ABTestConfig',
    'ABTestResult',
    'RollbackEvent',
    'RetrainingSchedule',
    'DriftTriggerEvaluator',
    'PerformanceMonitor',
    'ABTestManager',
    'RollbackManager',
    'TrainingJobQueue',
    'AutoRetrainingPipeline',
    'create_auto_retraining_pipeline',
    'create_ab_test_manager',
    'create_rollback_manager',
]
