"""
Geology Module for MineralVision Platform.

Provides comprehensive geological data management capabilities including:
- Drillhole database management (collar, survey, assay, lithology)
- QA/QC analysis (standards, blanks, duplicates, control charts)
- Cross-section generation (vertical, inclined, fence diagrams)
"""

from .drillhole_database import (
    DrillholeType,
    SurveyMethod,
    DesurveyMethod,
    CompositingMethod,
    ValidationSeverity,
    LithologyCode,
    CollarData,
    SurveyData,
    AssayData,
    LithologyData,
    GeotechnicalData,
    StructuralData,
    ValidationResult,
    DesurveySample,
    Composite,
    DrillholeValidator,
    DrillholeDesurveyor,
    DrillholeCompositor,
    DrillholeDatabase,
    create_drillhole_database,
)

from .qaqc_analysis import (
    QAQCType,
    ControlChartType,
    AlertLevel,
    FailureType,
    StandardReference,
    BlankReference,
    QAQCSample,
    ControlPoint,
    DuplicatePair,
    QAQCAlert,
    LabPerformance,
    StandardsAnalyzer,
    BlanksAnalyzer,
    DuplicatesAnalyzer,
    UmpireAnalyzer,
    QAQCDashboard,
    QAQCAnalyzer,
    create_qaqc_dashboard,
    create_qaqc_analyzer,
    create_standard_reference,
)

from .cross_sections import (
    SectionType,
    ProjectionMethod,
    DisplayMode,
    ColorScale,
    Point2D,
    Point3D,
    SectionLine,
    SectionExtent,
    ProjectedPoint,
    ProjectedInterval,
    DrillholeTrace,
    TopographyProfile,
    SectionAnnotation,
    GradeColorMap,
    Section,
    SectionGenerator,
    FenceDiagramGenerator,
    SectionExporter,
    create_section_generator,
    create_grade_color_map,
)

__all__ = [
    # Drillhole Database
    "DrillholeType",
    "SurveyMethod",
    "DesurveyMethod",
    "CompositingMethod",
    "ValidationSeverity",
    "LithologyCode",
    "CollarData",
    "SurveyData",
    "AssayData",
    "LithologyData",
    "GeotechnicalData",
    "StructuralData",
    "ValidationResult",
    "DesurveySample",
    "Composite",
    "DrillholeValidator",
    "DrillholeDesurveyor",
    "DrillholeCompositor",
    "DrillholeDatabase",
    "create_drillhole_database",
    # QA/QC Analysis
    "QAQCType",
    "ControlChartType",
    "AlertLevel",
    "FailureType",
    "StandardReference",
    "BlankReference",
    "QAQCSample",
    "ControlPoint",
    "DuplicatePair",
    "QAQCAlert",
    "LabPerformance",
    "StandardsAnalyzer",
    "BlanksAnalyzer",
    "DuplicatesAnalyzer",
    "UmpireAnalyzer",
    "QAQCDashboard",
    "QAQCAnalyzer",
    "create_qaqc_dashboard",
    "create_qaqc_analyzer",
    "create_standard_reference",
    # Cross Sections
    "SectionType",
    "ProjectionMethod",
    "DisplayMode",
    "ColorScale",
    "Point2D",
    "Point3D",
    "SectionLine",
    "SectionExtent",
    "ProjectedPoint",
    "ProjectedInterval",
    "DrillholeTrace",
    "TopographyProfile",
    "SectionAnnotation",
    "GradeColorMap",
    "Section",
    "SectionGenerator",
    "FenceDiagramGenerator",
    "SectionExporter",
    "create_section_generator",
    "create_grade_color_map",
]
