"""
Geology Module for MineralVision Platform.

Provides comprehensive geological data management capabilities including:
- Drillhole database management (collar, survey, assay, lithology)
- QA/QC analysis (standards, blanks, duplicates, control charts)
- Cross-section generation (vertical, inclined, fence diagrams)
"""

from .drillhole_database import (
    SurveyMethod,
    LithologyType,
    AlterationIntensity,
    MineralizationStyle,
    SampleType,
    CollarRecord,
    SurveyRecord,
    AssayRecord,
    LithologyRecord,
    GeotechnicalRecord,
    StructuralRecord,
    Drillhole,
    DrillholeDatabase,
    DrillholeValidator,
    DesurveySolver,
    CompositingEngine,
    DrillholeExporter,
    DrillholeDatabaseWorkflow,
    create_drillhole_database,
)

from .qaqc_analysis import (
    QAQCType,
    ControlStatus,
    LabPerformanceRating,
    StandardReference,
    BlankReference,
    DuplicatePair,
    QAQCResult,
    ControlChart,
    LabPerformance,
    StandardsAnalyzer,
    BlanksAnalyzer,
    DuplicatesAnalyzer,
    ControlChartGenerator,
    LabPerformanceAnalyzer,
    QAQCDashboard,
    QAQCWorkflow,
    create_qaqc_workflow,
)

from .cross_sections import (
    SectionType,
    ProjectionMethod,
    DisplayMode,
    SectionLine,
    ProjectedPoint,
    ProjectedInterval,
    DrillholeTrace,
    Section,
    TopographyProfile,
    SectionAnnotation,
    SectionGenerator,
    FenceDiagramGenerator,
    SectionExporter,
    CrossSectionWorkflow,
    create_cross_section_workflow,
)

__all__ = [
    # Drillhole Database
    "SurveyMethod",
    "LithologyType",
    "AlterationIntensity",
    "MineralizationStyle",
    "SampleType",
    "CollarRecord",
    "SurveyRecord",
    "AssayRecord",
    "LithologyRecord",
    "GeotechnicalRecord",
    "StructuralRecord",
    "Drillhole",
    "DrillholeDatabase",
    "DrillholeValidator",
    "DesurveySolver",
    "CompositingEngine",
    "DrillholeExporter",
    "DrillholeDatabaseWorkflow",
    "create_drillhole_database",
    # QA/QC Analysis
    "QAQCType",
    "ControlStatus",
    "LabPerformanceRating",
    "StandardReference",
    "BlankReference",
    "DuplicatePair",
    "QAQCResult",
    "ControlChart",
    "LabPerformance",
    "StandardsAnalyzer",
    "BlanksAnalyzer",
    "DuplicatesAnalyzer",
    "ControlChartGenerator",
    "LabPerformanceAnalyzer",
    "QAQCDashboard",
    "QAQCWorkflow",
    "create_qaqc_workflow",
    # Cross Sections
    "SectionType",
    "ProjectionMethod",
    "DisplayMode",
    "SectionLine",
    "ProjectedPoint",
    "ProjectedInterval",
    "DrillholeTrace",
    "Section",
    "TopographyProfile",
    "SectionAnnotation",
    "SectionGenerator",
    "FenceDiagramGenerator",
    "SectionExporter",
    "CrossSectionWorkflow",
    "create_cross_section_workflow",
]
