"""
Molmo2 Integration Module for MineralVision.

Provides video understanding, pixel-level grounding, multi-image reasoning,
and object tracking capabilities using Allen Institute's Molmo2-8B model.

Key Features:
- Video and multi-image understanding
- Pixel-level pointing and grounding
- Object tracking across video frames
- WALDO fusion for artisanal mining detection
- Drone video analysis for exploration
- V-JEPA integration for anomaly detection
"""

from .molmo_integration import (
    Molmo2Config,
    Molmo2Client,
    Molmo2Backend,
    AnalysisType,
    VideoAnalysisResult,
    PointingResult,
    TrackingResult,
    BoundingBox,
    create_molmo_client,
    analyze_mining_site_image,
    detect_artisanal_mining,
    compare_site_changes,
)
from .video_understanding import (
    VideoUnderstandingPipeline,
    VideoUnderstandingResult,
    FrameAnalysis,
    TemporalEvent,
    EventType,
    SceneType,
)
from .waldo_molmo_fusion import (
    WALDOMolmoFusion,
    FusedDetectionResult,
    FusionAnalysisResult,
    WALDODetection,
    MolmoUnderstanding,
    DetectionSource,
    ActivityType,
)
from .drone_video_analysis import (
    DroneVideoAnalyzer,
    FlightAnalysisResult,
    SiteChangeDetection,
    GeologicalObservation,
    GeologicalFeature,
    DroneMetadata,
    GeoLocation,
    FlightPattern,
    TerrainType,
)
from .vjepa_molmo_integration import (
    VJEPAMolmoFusion,
    FusedVideoAnalysis,
    VJEPAEmbedding,
    AnomalyDetection,
    FusionStrategy,
)
from .optimization import (
    StructuredOutput,
    StructuredOutputParser,
    PromptLibrary,
    DOMAIN_PROMPTS,
    QLoRAConfig,
    TrainingConfig,
    TrainingExample,
    FineTuningDataset,
    Molmo2FineTuner,
    AdapterInfo,
    MultiAdapterManager,
)
from .ensemble_pipeline import (
    DetectorType,
    SegmenterType,
    EmbedderType,
    ReasonerType,
    FrameResult,
    VideoResult,
    RFDETRDetector,
    EnsembleDetector,
    SAM3Segmenter,
    VJEPAEmbedder,
    Molmo2Reasoner,
    create_ensemble_pipeline,
    analyze_mining_video,
    analyze_geological_image,
)
from .evaluation import (
    GroundTruthFrame,
    GroundTruthVideo,
    GroundTruthSite,
    GroundTruthChange,
    PredictionFrame,
    PredictionSite,
    PredictionChange,
    SiteLevelMetrics,
    TrackingMetrics,
    ChangeDetectionMetrics,
    GeologicalMetrics,
    ComprehensiveMetrics,
    SiteLevelEvaluator,
    TrackingEvaluator,
    ChangeDetectionEvaluator,
    GeologicalEvaluator,
    ComprehensiveEvaluator,
    evaluate_geological_features,
    evaluate_change_detection,
    create_evaluation_report,
)

__all__ = [
    "Molmo2Config",
    "Molmo2Client",
    "Molmo2Backend",
    "AnalysisType",
    "VideoAnalysisResult",
    "PointingResult",
    "TrackingResult",
    "BoundingBox",
    "create_molmo_client",
    "analyze_mining_site_image",
    "detect_artisanal_mining",
    "compare_site_changes",
    "VideoUnderstandingPipeline",
    "VideoUnderstandingResult",
    "FrameAnalysis",
    "TemporalEvent",
    "EventType",
    "SceneType",
    "WALDOMolmoFusion",
    "FusedDetectionResult",
    "FusionAnalysisResult",
    "WALDODetection",
    "MolmoUnderstanding",
    "DetectionSource",
    "ActivityType",
    "DroneVideoAnalyzer",
    "FlightAnalysisResult",
    "SiteChangeDetection",
    "GeologicalObservation",
    "GeologicalFeature",
    "DroneMetadata",
    "GeoLocation",
    "FlightPattern",
    "TerrainType",
    "VJEPAMolmoFusion",
    "FusedVideoAnalysis",
    "VJEPAEmbedding",
    "AnomalyDetection",
    "FusionStrategy",
    "StructuredOutput",
    "StructuredOutputParser",
    "PromptLibrary",
    "DOMAIN_PROMPTS",
    "QLoRAConfig",
    "TrainingConfig",
    "TrainingExample",
    "FineTuningDataset",
    "Molmo2FineTuner",
    "AdapterInfo",
    "MultiAdapterManager",
    "DetectorType",
    "SegmenterType",
    "EmbedderType",
    "ReasonerType",
    "FrameResult",
    "VideoResult",
    "RFDETRDetector",
    "EnsembleDetector",
    "SAM3Segmenter",
    "VJEPAEmbedder",
    "Molmo2Reasoner",
    "create_ensemble_pipeline",
    "analyze_mining_video",
    "analyze_geological_image",
    "GroundTruthFrame",
    "GroundTruthVideo",
    "GroundTruthSite",
    "GroundTruthChange",
    "PredictionFrame",
    "PredictionSite",
    "PredictionChange",
    "SiteLevelMetrics",
    "TrackingMetrics",
    "ChangeDetectionMetrics",
    "GeologicalMetrics",
    "ComprehensiveMetrics",
    "SiteLevelEvaluator",
    "TrackingEvaluator",
    "ChangeDetectionEvaluator",
    "GeologicalEvaluator",
    "ComprehensiveEvaluator",
    "evaluate_geological_features",
    "evaluate_change_detection",
    "create_evaluation_report",
]
