"""Governance and temporal-consensus utilities for oil-spill intelligence.

JEPA is not treated as a detector or a source of fabricated confidence. If a caller supplies
real embeddings produced by a JEPA backend, this module uses them only to down-weight
frame outliers while fusing model-produced segmentation probability maps.
"""

from __future__ import annotations

from dataclasses import dataclass
from typing import Dict, Iterable, List, Optional, Sequence, Tuple

import numpy as np

from .schemas import EvaluationSplit, SegmentationMetrics

PROMOTION_THRESHOLDS = {
    "oil_f1": 0.97,
    "oil_iou": 0.95,
    "oil_precision": 0.97,
    "oil_recall": 0.97,
}
MIN_SEALED_HOLDOUT_SAMPLES = 100


@dataclass(frozen=True)
class PromotionEligibility:
    """A transparent promotion decision derived from recorded sealed evaluations."""

    eligible: bool
    reasons: List[str]


def evaluate_promotion_eligibility(
    evaluations: Iterable[Tuple[str, EvaluationSplit, int, Dict[str, float]]],
    intended_domains: Sequence[str],
) -> PromotionEligibility:
    """Apply the formal per-domain sealed-holdout gate without inventing performance.

    Each intended domain needs at least one recorded sealed-holdout run with the minimum
    sample count. Every required oil-class metric must meet the documented threshold.
    """
    evidence_by_domain: Dict[str, List[Tuple[int, Dict[str, float]]]] = {}
    for domain, split, sample_count, metrics in evaluations:
        if split == EvaluationSplit.SEALED_HOLDOUT:
            evidence_by_domain.setdefault(domain, []).append((sample_count, metrics))

    reasons: List[str] = []
    for domain in intended_domains:
        runs = evidence_by_domain.get(domain, [])
        if not runs:
            reasons.append(f"No sealed-holdout evaluation exists for intended domain '{domain}'")
            continue
        qualifying_run_found = False
        for sample_count, metrics in runs:
            if sample_count < MIN_SEALED_HOLDOUT_SAMPLES:
                continue
            failures = [
                f"{metric_name}={metrics.get(metric_name)!r} is below {threshold:.2f}"
                for metric_name, threshold in PROMOTION_THRESHOLDS.items()
                if metrics.get(metric_name) is None or float(metrics[metric_name]) < threshold
            ]
            if not failures:
                qualifying_run_found = True
                break
        if not qualifying_run_found:
            reasons.append(
                f"No sealed-holdout run for '{domain}' meets all promotion thresholds "
                f"with at least {MIN_SEALED_HOLDOUT_SAMPLES} samples"
            )

    return PromotionEligibility(eligible=not reasons, reasons=reasons)


@dataclass(frozen=True)
class TemporalConsensusResult:
    """Fused probability map and diagnostics for a sequence of aligned frames."""

    probability_map: np.ndarray
    frame_weights: List[float]
    temporal_stability: float
    used_jepa_embeddings: bool
    quality_flags: List[str]


def _normalized_embedding_weights(embeddings: np.ndarray) -> np.ndarray:
    """Down-weight temporally inconsistent frames using supplied real embeddings."""
    norms = np.linalg.norm(embeddings, axis=1, keepdims=True)
    if np.any(norms == 0):
        raise ValueError("JEPA embeddings must not contain zero-length vectors")
    normalized = embeddings / norms
    centroid = normalized.mean(axis=0)
    centroid_norm = np.linalg.norm(centroid)
    if centroid_norm == 0:
        raise ValueError("JEPA embedding centroid has zero length")
    centroid /= centroid_norm
    similarity = np.clip(normalized @ centroid, -1.0, 1.0)
    # Map cosine similarity to small positive weights; the result is normalized below.
    raw = np.maximum((similarity + 1.0) / 2.0, 0.05)
    return raw / raw.sum()


def fuse_temporal_probabilities(
    probability_maps: Sequence[np.ndarray],
    *,
    jepa_embeddings: Optional[Sequence[Sequence[float]]] = None,
) -> TemporalConsensusResult:
    """Fuse aligned frame probability maps, optionally weighted by real JEPA embeddings.

    The function never calls a JEPA model and never fabricates embeddings. Callers that want
    JEPA-aware fusion must provide embeddings generated by an approved JEPA backend for the
    same frame sequence. A median fusion fallback is used when no embeddings are supplied.
    """
    if len(probability_maps) < 2:
        raise ValueError("At least two aligned probability maps are required for temporal consensus")
    arrays = [np.asarray(probability_map, dtype=np.float32) for probability_map in probability_maps]
    shape = arrays[0].shape
    if len(shape) != 2 or any(array.shape != shape for array in arrays):
        raise ValueError("All probability maps must be aligned, 2-D arrays with identical dimensions")
    if any(not np.isfinite(array).all() or array.min() < 0 or array.max() > 1 for array in arrays):
        raise ValueError("Probability maps must contain finite values in [0, 1]")

    stacked = np.stack(arrays, axis=0)
    flags: List[str] = []
    used_jepa_embeddings = jepa_embeddings is not None
    if jepa_embeddings is None:
        fused = np.median(stacked, axis=0)
        weights = np.full(len(arrays), 1 / len(arrays), dtype=np.float32)
        flags.append("jepa_embeddings_not_supplied_median_fusion_used")
    else:
        embedding_array = np.asarray(jepa_embeddings, dtype=np.float32)
        if embedding_array.ndim != 2 or embedding_array.shape[0] != len(arrays):
            raise ValueError("JEPA embedding count must equal the number of probability maps")
        if not np.isfinite(embedding_array).all():
            raise ValueError("JEPA embeddings must contain only finite values")
        weights = _normalized_embedding_weights(embedding_array)
        fused = np.tensordot(weights, stacked, axes=(0, 0))

    # Stability is one minus the mean per-pixel standard deviation across the sequence.
    temporal_stability = float(np.clip(1.0 - stacked.std(axis=0).mean(), 0.0, 1.0))
    if temporal_stability < 0.8:
        flags.append("low_temporal_stability_requires_review")
    return TemporalConsensusResult(
        probability_map=fused.astype(np.float32),
        frame_weights=[round(float(weight), 6) for weight in weights],
        temporal_stability=round(temporal_stability, 6),
        used_jepa_embeddings=used_jepa_embeddings,
        quality_flags=flags,
    )
