from fastapi import APIRouter, HTTPException, Depends, Query
from typing import List, Dict, Any, Optional
from pydantic import BaseModel
from datetime import datetime
import json

# Heavy geospatial dependencies (shapely) are optional. The API boots
# without them; these endpoints degrade with HTTP 503.
try:
    from ..autonomous_exploration.core import (
        AutonomousExplorationSystem,
        DroneSpecification,
        DroneState,
        SamplingPoint,
        MissionPlan,
        ExplorationArea
    )
    AUTONOMOUS_EXPLORATION_AVAILABLE = True
    _AUTONOMOUS_EXPLORATION_ERROR: Optional[str] = None
except ImportError as exc:  # pragma: no cover - depends on optional deps
    AutonomousExplorationSystem = DroneSpecification = DroneState = None
    SamplingPoint = MissionPlan = ExplorationArea = None
    AUTONOMOUS_EXPLORATION_AVAILABLE = False
    _AUTONOMOUS_EXPLORATION_ERROR = str(exc)


def _require_autonomous_exploration():
    """Raise HTTP 503 when the geospatial stack is not installed."""
    if not AUTONOMOUS_EXPLORATION_AVAILABLE:
        raise HTTPException(
            status_code=503,
            detail=(
                "Autonomous exploration is unavailable: optional geospatial "
                "dependencies are not installed "
                f"({_AUTONOMOUS_EXPLORATION_ERROR}). Install the optional "
                "geospatial requirements to enable this feature."
            )
        )


# Initialize the autonomous exploration system
autonomous_system = AutonomousExplorationSystem() if AUTONOMOUS_EXPLORATION_AVAILABLE else None

router = APIRouter(
    prefix="/autonomous-exploration",
    tags=["autonomous-exploration"],
    responses={404: {"description": "Not found"}},
    dependencies=[Depends(_require_autonomous_exploration)],
)

# Request and response models
class DroneSpecificationRequest(BaseModel):
    model: str
    battery_capacity_mah: int
    max_flight_time_minutes: int
    max_speed_mps: float
    max_payload_grams: int
    camera_resolution: str
    sensors: List[str]
    communication_range_meters: int

class DroneStateRequest(BaseModel):
    position: Dict[str, float]
    battery_percentage: float
    status: str
    payload_status: str
    current_mission_id: Optional[str] = None

class SamplingPointRequest(BaseModel):
    position: Dict[str, float]
    priority: int
    sample_type: str
    estimated_time_seconds: int

class ExplorationAreaRequest(BaseModel):
    name: str
    geometry: Dict[str, Any]
    priority: int

class SwarmMissionRequest(BaseModel):
    area_id: str
    num_drones: int = 3

class AdaptiveSamplingRequest(BaseModel):
    area_id: str
    initial_results: Dict[str, float]

class MissionResponse(BaseModel):
    mission_id: str
    drone_id: str
    waypoints: List[Dict[str, float]]
    sampling_points: List[str]
    estimated_duration_minutes: float
    battery_requirement_percentage: float
    status: str
    start_time: Optional[datetime] = None
    end_time: Optional[datetime] = None

class DroneAssignmentResponse(BaseModel):
    assignments: Dict[str, List[str]]

# Drone management endpoints
@router.post("/drones", response_model=Dict[str, str])
async def register_drone(drone_spec: DroneSpecificationRequest):
    """Register a new drone in the system."""
    spec = DroneSpecification(
        drone_id="",  # Will be generated by the system
        **drone_spec.dict()
    )
    drone_id = autonomous_system.register_drone(spec)
    return {"drone_id": drone_id}

@router.get("/drones", response_model=List[DroneSpecification])
async def get_all_drones():
    """Get all registered drones."""
    return autonomous_system.get_all_drones()

@router.get("/drones/{drone_id}", response_model=DroneSpecification)
async def get_drone(drone_id: str):
    """Get drone specification by ID."""
    drone = autonomous_system.get_drone(drone_id)
    if not drone:
        raise HTTPException(status_code=404, detail="Drone not found")
    return drone

@router.put("/drones/{drone_id}/state", response_model=Dict[str, bool])
async def update_drone_state(drone_id: str, state_request: DroneStateRequest):
    """Update the state of a drone."""
    state = DroneState(
        drone_id=drone_id,
        **state_request.dict()
    )
    success = autonomous_system.update_drone_state(state)
    if not success:
        raise HTTPException(status_code=404, detail="Drone not found")
    return {"success": success}

@router.get("/drones/{drone_id}/state", response_model=DroneState)
async def get_drone_state(drone_id: str):
    """Get current state of a drone by ID."""
    state = autonomous_system.get_drone_state(drone_id)
    if not state:
        raise HTTPException(status_code=404, detail="Drone state not found")
    return state

@router.get("/drones/available", response_model=List[str])
async def get_available_drones():
    """Get IDs of drones available for missions."""
    return autonomous_system.get_available_drones()

# Sampling point endpoints
@router.post("/sampling-points", response_model=Dict[str, str])
async def add_sampling_point(point_request: SamplingPointRequest):
    """Add a new sampling point."""
    point = SamplingPoint(
        point_id="",  # Will be generated by the system
        status="pending",
        assigned_drone_id=None,
        **point_request.dict()
    )
    point_id = autonomous_system.add_sampling_point(point)
    return {"point_id": point_id}

@router.get("/sampling-points", response_model=List[SamplingPoint])
async def get_all_sampling_points():
    """Get all sampling points."""
    return autonomous_system.get_all_sampling_points()

@router.get("/sampling-points/{point_id}", response_model=SamplingPoint)
async def get_sampling_point(point_id: str):
    """Get a sampling point by ID."""
    point = autonomous_system.get_sampling_point(point_id)
    if not point:
        raise HTTPException(status_code=404, detail="Sampling point not found")
    return point

@router.get("/sampling-points/pending", response_model=List[SamplingPoint])
async def get_pending_sampling_points():
    """Get sampling points that are pending assignment."""
    return autonomous_system.get_pending_sampling_points()

# Mission planning endpoints
@router.post("/missions", response_model=Dict[str, str])
async def create_mission_plan(drone_id: str, sampling_point_ids: List[str]):
    """Create a mission plan for a drone to visit sampling points."""
    mission_id = autonomous_system.create_mission_plan(drone_id, sampling_point_ids)
    if not mission_id:
        raise HTTPException(status_code=400, detail="Failed to create mission plan")
    return {"mission_id": mission_id}

@router.post("/missions/{mission_id}/start", response_model=Dict[str, bool])
async def start_mission(mission_id: str):
    """Start a planned mission."""
    success = autonomous_system.start_mission(mission_id)
    if not success:
        raise HTTPException(status_code=400, detail="Failed to start mission")
    return {"success": success}

@router.post("/missions/{mission_id}/complete", response_model=Dict[str, bool])
async def complete_mission(mission_id: str, success: bool = True):
    """Mark a mission as completed or failed."""
    result = autonomous_system.complete_mission(mission_id, success)
    if not result:
        raise HTTPException(status_code=400, detail="Failed to complete mission")
    return {"success": result}

@router.get("/missions/{mission_id}", response_model=MissionResponse)
async def get_mission_plan(mission_id: str):
    """Get a mission plan by ID."""
    mission = autonomous_system.get_mission_plan(mission_id)
    if not mission:
        raise HTTPException(status_code=404, detail="Mission plan not found")
    return mission

@router.get("/missions", response_model=List[MissionResponse])
async def get_all_mission_plans():
    """Get all mission plans."""
    return autonomous_system.get_all_mission_plans()

@router.get("/drones/{drone_id}/missions", response_model=List[MissionResponse])
async def get_drone_missions(drone_id: str):
    """Get all missions for a specific drone."""
    return autonomous_system.get_drone_missions(drone_id)

# Exploration area endpoints
@router.post("/exploration-areas", response_model=Dict[str, str])
async def add_exploration_area(area_request: ExplorationAreaRequest):
    """Add a new exploration area."""
    area = ExplorationArea(
        area_id="",  # Will be generated by the system
        exploration_status="pending",
        completion_percentage=0.0,
        **area_request.dict()
    )
    area_id = autonomous_system.add_exploration_area(area)
    return {"area_id": area_id}

@router.get("/exploration-areas", response_model=List[ExplorationArea])
async def get_all_exploration_areas():
    """Get all exploration areas."""
    return autonomous_system.get_all_exploration_areas()

@router.get("/exploration-areas/{area_id}", response_model=ExplorationArea)
async def get_exploration_area(area_id: str):
    """Get an exploration area by ID."""
    area = autonomous_system.get_exploration_area(area_id)
    if not area:
        raise HTTPException(status_code=404, detail="Exploration area not found")
    return area

# Advanced planning endpoints
@router.post("/exploration-areas/{area_id}/sampling-points", response_model=List[str])
async def generate_sampling_points_for_area(area_id: str, density: float = 0.0001):
    """Generate sampling points for an exploration area based on density."""
    point_ids = autonomous_system.generate_sampling_points_for_area(area_id, density)
    if not point_ids:
        raise HTTPException(status_code=400, detail="Failed to generate sampling points")
    return point_ids

@router.post("/optimize-assignments", response_model=DroneAssignmentResponse)
async def optimize_drone_assignments():
    """Optimize assignment of drones to sampling points using Hungarian algorithm."""
    assignments = autonomous_system.optimize_drone_assignments()
    return {"assignments": assignments}

@router.post("/swarm-mission", response_model=List[str])
async def generate_swarm_mission(request: SwarmMissionRequest):
    """Generate coordinated missions for a swarm of drones to explore an area."""
    mission_ids = autonomous_system.generate_swarm_mission(request.area_id, request.num_drones)
    if not mission_ids:
        raise HTTPException(status_code=400, detail="Failed to generate swarm mission")
    return mission_ids

@router.post("/adaptive-sampling", response_model=List[str])
async def adaptive_sampling_strategy(request: AdaptiveSamplingRequest):
    """Generate adaptive sampling points based on initial results."""
    point_ids = autonomous_system.adaptive_sampling_strategy(request.area_id, request.initial_results)
    if not point_ids:
        raise HTTPException(status_code=400, detail="Failed to generate adaptive sampling points")
    return point_ids
