apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: waldo-models-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: waldo-data-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
---
apiVersion: v1
kind: Secret
metadata:
  name: waldo-secrets
type: Opaque
data:
  database-uri: cG9zdGdyZXNxbDovL21pbmVyYWx2aXNpb246cGFzc3dvcmRAZGF0YWJhc2U6NTQzMi93YWxkb19kZXRlY3Rpb25z
  rabbitmq-uri: YW1xcDovL21pbmVyYWx2aXNpb246cGFzc3dvcmRAbWVzc2FnZS1icm9rZXI6NTY3Mi8=
  arcgis-url: aHR0cHM6Ly9hcmNnaXMuZXhhbXBsZS5jb20=
  arcgis-username: bWluZXJhbHZpc2lvbg==
  arcgis-password: cGFzc3dvcmQ=
