"""
MineralVision Machine Learning Module.

This module provides comprehensive ML capabilities for mineral exploration including:
- Prospectivity mapping with spatial cross-validation
- Feature generation from geospatial raster stacks
- NLP extraction from geological reports
- Dataset registry and benchmarking
- Spatially-aware evaluation metrics
"""

from .prospectivity_workflow import (
    ValidationStrategy,
    ProspectivityModel,
    TrainingPoint,
    ProspectivityDataset,
    SpatialBufferCV,
    create_benchmark_dataset,
)

from .gold_exploration import (
    AlterationType,
    RegolithType,
    GoldOccurrence,
    StructuralFeature,
    AlterationIndices,
    RegolithModel,
    StructuralComplexity,
    GoldDepositPriors,
    create_synthetic_gold_dataset,
)

from .lithium_exploration import (
    LithiumMineral,
    BrineType,
    WellData,
    PegmatiteSample,
    BrineChemistry,
    HydrogeologyModel,
    ClayLithiumAnalysis,
    LithiumDepositPriors,
    create_synthetic_lithium_dataset,
)

from .soil_suitability import (
    SuitabilityClass,
    SoilTextureClass,
    DrainageClass,
    ClimateData,
    TopographyData,
    SoilSuitabilityScorer,
    RemediationRecommender,
    create_synthetic_soil_dataset,
)

from .advanced_soil_assessment import (
    ToxicityType,
    DiseaseRiskType,
    PhosphorusMethod,
    ToxicityHazard,
    NutrientBudget,
    UncertaintyEstimate,
    WaterBalanceResult,
    DiseaseRiskAssessment,
    EconomicAnalysis,
    NutrientBudgetCalculator,
    PhysicalConstraintAssessor,
    UncertaintyQuantifier,
    WaterBalanceCalculator,
    DiseaseRiskAssessor,
    EconomicAnalyzer,
    SpatialInterpolator,
)

from .uncover_ml import (
    UncoverMLPipeline,
    ProspectivityWorkflow,
    FeatureEngineering,
    ModelEnsemble,
    UncertaintyQuantification,
    RasterStack,
    TrainingData,
    PredictionResult,
    FeatureScale,
    AggregationType,
    ModelType,
)

from .torchgeo_models import (
    GeoFoundationModel,
    SatelliteImageProcessor,
    UAVImageProcessor,
    PretrainedBackbone,
    FoundationModelType,
    ImageryType,
    TaskType,
    ImageBatch,
    ModelOutput,
    create_geo_foundation_model,
)

from .spatial_cv import (
    SpatialCrossValidator,
    BlockCV,
    BufferedLeaveOneOut,
    SpatialKFold,
    CVStrategy,
    CVFold,
    CVResult,
    validate_spatial_model,
)

from .uncertainty_quantification import (
    UncertaintyType,
    ConfidenceLevel,
    SensitivityResult,
    CalibrationResult,
    MCDropoutEstimator,
    DeepEnsembleEstimator,
    QuantileRegressionEstimator,
    SobolSensitivityAnalyzer,
    CalibrationAssessor,
    UncertaintyPropagator,
    UncertaintyQuantificationPipeline,
    create_uq_pipeline,
    estimate_grid_uncertainty,
)

from .mlops_hardening import (
    ModelStage,
    DatasetType,
    DriftType,
    DatasetVersion,
    ExperimentRun,
    ModelCard,
    DriftAlert,
    DatasetVersionManager,
    ExperimentTracker,
    DriftMonitor,
    EvaluationSuite,
    MLOpsPipeline,
    create_mlops_pipeline,
    create_experiment_tracker,
    create_drift_monitor,
)

from .foundation_models import (
    DataModality,
    PretrainingTask,
    FineTuningStrategy,
    ModalityConfig,
    PretrainingConfig,
    FineTuningConfig,
    ModelCheckpoint,
    ModalityAdapter,
    MultispectralAdapter,
    GeophysicsAdapter,
    TextAdapter,
    PretrainingPipeline,
    FineTuningPipeline,
    GeoscienceFoundationModel,
    FoundationModelRegistry,
    create_foundation_model,
    create_pretraining_config,
    create_finetuning_config,
)

__all__ = [
    "ValidationStrategy",
    "ProspectivityModel",
    "TrainingPoint",
    "ProspectivityDataset",
    "SpatialBufferCV",
    "create_benchmark_dataset",
    "AlterationType",
    "RegolithType",
    "GoldOccurrence",
    "StructuralFeature",
    "AlterationIndices",
    "RegolithModel",
    "StructuralComplexity",
    "GoldDepositPriors",
    "create_synthetic_gold_dataset",
    "LithiumMineral",
    "BrineType",
    "WellData",
    "PegmatiteSample",
    "BrineChemistry",
    "HydrogeologyModel",
    "ClayLithiumAnalysis",
    "LithiumDepositPriors",
    "create_synthetic_lithium_dataset",
    "SuitabilityClass",
    "SoilTextureClass",
    "DrainageClass",
    "ClimateData",
    "TopographyData",
    "SoilSuitabilityScorer",
    "RemediationRecommender",
    "create_synthetic_soil_dataset",
    "ToxicityType",
    "DiseaseRiskType",
    "PhosphorusMethod",
    "ToxicityHazard",
    "NutrientBudget",
    "UncertaintyEstimate",
    "WaterBalanceResult",
    "DiseaseRiskAssessment",
    "EconomicAnalysis",
    "NutrientBudgetCalculator",
    "PhysicalConstraintAssessor",
    "UncertaintyQuantifier",
    "WaterBalanceCalculator",
    "DiseaseRiskAssessor",
    "EconomicAnalyzer",
    "SpatialInterpolator",
    "UncoverMLPipeline",
    "ProspectivityWorkflow",
    "FeatureEngineering",
    "ModelEnsemble",
    "UncertaintyQuantification",
    "RasterStack",
    "TrainingData",
    "PredictionResult",
    "FeatureScale",
    "AggregationType",
    "ModelType",
    "GeoFoundationModel",
    "SatelliteImageProcessor",
    "UAVImageProcessor",
    "PretrainedBackbone",
    "FoundationModelType",
    "ImageryType",
    "TaskType",
    "ImageBatch",
    "ModelOutput",
    "create_geo_foundation_model",
    "SpatialCrossValidator",
    "BlockCV",
    "BufferedLeaveOneOut",
    "SpatialKFold",
    "CVStrategy",
    "CVFold",
    "CVResult",
    "validate_spatial_model",
    "UncertaintyType",
    "ConfidenceLevel",
    "SensitivityResult",
    "CalibrationResult",
    "MCDropoutEstimator",
    "DeepEnsembleEstimator",
    "QuantileRegressionEstimator",
    "SobolSensitivityAnalyzer",
    "CalibrationAssessor",
    "UncertaintyPropagator",
    "UncertaintyQuantificationPipeline",
    "create_uq_pipeline",
    "estimate_grid_uncertainty",
    "ModelStage",
    "DatasetType",
    "DriftType",
    "DatasetVersion",
    "ExperimentRun",
    "ModelCard",
    "DriftAlert",
    "DatasetVersionManager",
    "ExperimentTracker",
    "DriftMonitor",
    "EvaluationSuite",
    "MLOpsPipeline",
    "create_mlops_pipeline",
    "create_experiment_tracker",
    "create_drift_monitor",
    "DataModality",
    "PretrainingTask",
    "FineTuningStrategy",
    "ModalityConfig",
    "PretrainingConfig",
    "FineTuningConfig",
    "ModelCheckpoint",
    "ModalityAdapter",
    "MultispectralAdapter",
    "GeophysicsAdapter",
    "TextAdapter",
    "PretrainingPipeline",
    "FineTuningPipeline",
    "GeoscienceFoundationModel",
    "FoundationModelRegistry",
    "create_foundation_model",
    "create_pretraining_config",
    "create_finetuning_config",
]
