"""Tests for the inversion job service (full lifecycle on a tiny mesh)."""

import numpy as np
import pytest
from fastapi import FastAPI
from fastapi.testclient import TestClient
from sqlalchemy import create_engine
from sqlalchemy.orm import sessionmaker
from sqlalchemy.pool import StaticPool

from api.innovations.inversion_jobs import router
from api.innovations.inversion_jobs.models import Base, get_session
from api.innovations.inversion_jobs import logic


@pytest.fixture()
def client():
    """App with an in-memory SQLite job store (shared via StaticPool)."""
    engine = create_engine(
        "sqlite://", connect_args={"check_same_thread": False},
        poolclass=StaticPool)
    Base.metadata.create_all(engine)
    factory = sessionmaker(bind=engine, expire_on_commit=False)

    def override_session():
        s = factory()
        try:
            yield s
        finally:
            s.close()

    app = FastAPI()
    app.include_router(router)
    app.dependency_overrides[get_session] = override_session
    with TestClient(app) as c:  # lifespan + background tasks run to completion
        yield c


def _payload(**overrides):
    """Tiny gravity inversion: 4x3x3 mesh, 8 surface observations.

    Observed data generated by forward-modelling a buried anomaly so the
    inversion has a real signal to recover.
    """
    payload = {
        "mesh": {"origin": [0, 0, 0], "cell_sizes": [10, 10, 10],
                 "n_cells": [4, 3, 3]},
        "survey": {"name": "tiny", "survey_type": "gravity",
                   "observations": []},
        "parameters": {"max_iterations": 40, "target_misfit": 1e-4},
    }
    # build synthetic observations with the core forward model
    from api.geophysics.inversion import (InversionMesh, SurveyData,
        ObservationPoint, Point3D, InversionType, ForwardModeler)
    mesh = InversionMesh(origin=Point3D(0, 0, 0), cell_sizes=(10, 10, 10),
                         n_cells=(4, 3, 3))
    true = np.zeros(len(mesh.cells))
    true[18] = 1.0  # second-layer anomaly centred under x=25, y=15
    obs = []
    for i in range(4):
        for j in range(2):
            obs.append(ObservationPoint(
                location=Point3D(5 + 10 * i, 5 + 10 * j, 10),
                observed_value=0.0, uncertainty=1.0))
    survey = SurveyData(name="gen", survey_type=InversionType.GRAVITY,
                        observations=obs)
    fm = ForwardModeler(mesh, survey)
    d = fm.forward(true)
    # scale the anomaly so the observed signal is O(10) — the gravity kernel
    # is ~1e-5, and a well-scaled problem exercises the solver for real.
    true[14] = 10.0 / np.abs(d).max()
    d = fm.forward(true)
    payload["survey"]["observations"] = [
        {"x": o.location.x, "y": o.location.y, "z": o.location.z,
         "value": float(v), "uncertainty": 1.0}
        for o, v in zip(obs, d)]
    payload.update(overrides)
    return payload


def test_full_lifecycle_submit_to_completed(client):
    r = client.post("/innovations/inversion_jobs/jobs", json=_payload())
    assert r.status_code == 201
    job_id = r.json()["job_id"]
    assert r.json()["status"] in ("pending", "running")

    # TestClient waits for BackgroundTasks -> job must be completed now.
    r = client.get(f"/innovations/inversion_jobs/jobs/{job_id}")
    assert r.status_code == 200
    job = r.json()
    assert job["status"] == "completed"
    assert job["progress"] == 1.0
    assert job["error"] is None
    assert job["has_result"] is True

    # Result artifact: real inversion output.
    r = client.get(f"/innovations/inversion_jobs/jobs/{job_id}/result")
    assert r.status_code == 200
    result = r.json()
    assert isinstance(result["success"], bool)
    assert len(result["final_model"]) == 36      # 4x3x3 mesh
    assert len(result["predicted_data"]) == 8
    assert len(result["convergence_history"]) >= 1

    # Real compute checks: the Gauss-Newton run must (a) reduce the data
    # misfit strongly vs the zero model, and (b) place the dominant model
    # cell at the lateral position of the planted anomaly (x=25, y=15).
    obs = np.array([o["value"] for o in _payload()["survey"]["observations"]])
    initial_misfit = float(np.mean(obs ** 2))
    assert result["data_misfit"] < 0.3 * initial_misfit

    model = np.array(result["final_model"])
    assert np.abs(model).max() > 0.0
    peak = int(np.argmax(model))
    peak_ix = peak % 4
    peak_iz = peak // 12
    assert peak_ix == 2           # above the planted anomaly (x=25)
    assert peak_iz <= 1           # depth-smearing limited to the top 2 layers
    # the predicted data maximum sits at one of the two stations straddling
    # the anomaly centre (stations 4 and 5: x=25, y=5/15)
    pred = np.array(result["predicted_data"])
    assert int(np.argmax(pred)) in (4, 5)
    assert int(np.argmax(obs)) in (4, 5)

    # Artifact download endpoint.
    r = client.get(f"/innovations/inversion_jobs/jobs/{job_id}/artifact")
    assert r.status_code == 200
    assert "attachment" in r.headers["content-disposition"]
    assert r.json()["final_model"] == result["final_model"]


def test_failed_job_records_error(client):
    bad = _payload()
    bad["survey"]["survey_type"] = "not_a_method"
    r = client.post("/innovations/inversion_jobs/jobs", json=bad)
    assert r.status_code == 201
    job_id = r.json()["job_id"]

    r = client.get(f"/innovations/inversion_jobs/jobs/{job_id}")
    job = r.json()
    assert job["status"] == "failed"
    assert "not_a_method" in job["error"]

    # Result of a failed job -> 409 with the recorded error.
    r = client.get(f"/innovations/inversion_jobs/jobs/{job_id}/result")
    assert r.status_code == 409
    assert "not_a_method" in r.json()["detail"]


def test_two_concurrent_jobs(client):
    ids = []
    for _ in range(2):
        r = client.post("/innovations/inversion_jobs/jobs", json=_payload())
        assert r.status_code == 201
        ids.append(r.json()["job_id"])
    assert ids[0] != ids[1]
    for job_id in ids:
        job = client.get(f"/innovations/inversion_jobs/jobs/{job_id}").json()
        assert job["status"] == "completed"
    r = client.get("/innovations/inversion_jobs/jobs")
    assert r.json()["n_jobs"] == 2


def test_unknown_job_404(client):
    r = client.get("/innovations/inversion_jobs/jobs/does-not-exist")
    assert r.status_code == 404


def test_compute_validation_errors():
    with pytest.raises(ValueError, match="survey_type"):
        logic.run_inversion_compute(
            {"mesh": {"origin": [0, 0, 0], "cell_sizes": [1, 1, 1],
                      "n_cells": [2, 2, 2]},
             "survey": {"survey_type": "bogus",
                        "observations": [{"x": 0, "y": 0, "z": 0,
                                          "value": 1.0}]}})
    with pytest.raises(ValueError, match="observation"):
        logic.run_inversion_compute(
            {"mesh": {"origin": [0, 0, 0], "cell_sizes": [1, 1, 1],
                      "n_cells": [2, 2, 2]},
             "survey": {"survey_type": "gravity", "observations": []}})
